### PR TITLE
adding missing images, and src for images

### PR DESCRIPTION
**Pull request by rubychilds**

### CODE REVIEW

**Comment by kynan** [comment]
Seems you re-added the huge images, that kind of defeated what I did in #3 ;)

**Comment by kynan** [comment]
I can amend the commit if you like. You would then need to hard reset your local master branch i.e.

    git fetch
    git reset --hard origin/master

Let me know if you want me to do that.

**Comment by rubychilds** [comment]
No please don't do that as I've corrected other bits also. I can do it
later today. Also you should try avoid hard resets and use soft

**Comment by kynan** [comment]
That wouldn't help. I was suggesting to rewrite that commit because that's the only way to not have those large files in the repo's history.

**Comment by rubychilds** [comment]
It's fine. I'll change it

**Pull request merged**
